name: 360events
favicon: null
layout_spectrum: 0.13070674240589142
typography_spectrum: 0.43221597047522664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6957214470021427
  lightness: 0.7562919920310378
  saturation: 0.039171762531623244
  rhythmicContrast: 0.43076327722519636
purpose: []
